alias l='ls -alF'
alias ll='ls -alFrth'
alias cdv='cdvirtualenv'
alias cdsp='cdsitepackages'
alias cdp='cdproject'
alias ..='cd ..'
alias ...='cd .. && cd ..'
alias o='less -R'
alias gl='clear && git lnp'
alias gll='git l'
alias gs='git st'
alias ga='git ap'
alias gc='git ci -m'
alias gu='git up'

